line:
	cc  ./MAIN/*.c ./BUILTINS/Builtin_pwd.c ./BUILTINS/Builtin_cd.c ./PARSING/*.c ./ENVIRONMENT/*.c  ./SIGNALS/*.c String_Utils.c -g3  -lreadline -o minishell -Wall -Werror -Wextra -fsanitize=address,unreachable
