line:
	cc  ./MAIN/*.c ./BUILTINS/Builtin_unset.c ./BUILTINS/Builtin_export.c ./BUILTINS/Exit_code.c ./BUILTINS/Builtin_env.c ./PARSING/*.c ./ENVIRONMENT/*.c  ./SIGNALS/*.c String_Utils.c -g3  -lreadline -o minishell -Wall -Werror -Wextra -fsanitize=address,unreachable
